### ISSUE TITLE
Add other mining services to blacklist.txt

### ISSUE THREAD

**Issue by shmishtopher** [shmishtopher/CoinBlock#3]
There are quite a few other services that aren't in the blacklist yet, any additions are appreciated.

**Comment by harrisonlingren** [comment]
Opened PR #4 for this

**Comment by shmishtopher** [comment]
ill just keep this issue open for any future additions, good work @harrisonlingren

**Comment by dhavdc** [comment]
I also added a few more services.

**Comment by phr34k0** [comment]
![screenshot_20171105-100258](https://user-images.githubusercontent.com/13272249/32411235-ee34d0f0-c210-11e7-8fee-534bd90f1f74.png)

Add these please! Thanks
